### ISSUE TITLE
Question: can 32 byte shared secret can be given as input to HKDF-SHA512?

### ISSUE THREAD

**Issue by evil-user** [samuel-lucas6/Cryptography-Guidelines#2]
Hi @samuel-lucas6  , since digest size of sha512 is 512 bits or 64 bytes , is it safe to use values lower than 64 bytes as input to hkdf?
I learned than hkdf uses hmac internally and input for hmac-512 is recommended to be equal to digest size that is 64 bytes.

**Comment by samuel-lucas6** [comment]
Good question and something I should probably clarify.

Yes, the input keying material can be less than the digest size for HKDF-Extract. However, the key for HKDF-Expand is meant to be as long as the digest size based on the [RFC](https://www.rfc-editor.org/rfc/rfc5869#section-2.2).

If you're only deriving one key, you should be calling a function that does both steps for you, meaning the 32 byte shared secret will get converted into a 64 byte pseudorandom key internally.

Hope that helps!

**Comment by samuel-lucas6** [comment]
I'm guessing [this](https://crypto.stackexchange.com/questions/101159/can-32-byte-shared-secret-can-be-given-as-input-to-hkdf-sha512/101167#101167) is also your question. I've answered there with some extra detail.

Specifically, with a shared secret, it's important to call HKDF-Extract first because the shared secret won't be uniformly random.
