### ISSUE TITLE
Question about your recommendation on salted Blake2b as HKDF

### ISSUE THREAD

**Issue by BigPanda97** [samuel-lucas6/Cryptography-Guidelines#6]
In your guidelines, you recommend salted Blake2b as (Non-Password-Based) Key Derivation Function; however, there are the parameters salt, personalization, and you wrote that you can even feed more context information into the message parameter, but you haven't made any examples, on when you should put which sort of data into which parameter.
Let's say, for example, that you have one key (from Argon2) and for whatever reason, you need to combine 4 ciphers, and therefore you need 4 x 256 bit of key material. Would it then be correct to use something like “cipher1”, “cipher2”, “cipher3” and “cipher4” as the personalization, the key from Argon2 as the message and just leave the salt blank (null)? Or what would be the correct usage here?

And just out of curiosity, wouldn't it be possible too, to just use the key from Argon2 for ChaCha20 with a nonce of zero to generate 1024 bits of key stream, and then split the 1024-bit into 4 chunks with 256 bit each and just use them as keys for the 4 ciphers? Or would this lower the security compared to using Blake2b with the parameters?

**Comment by samuel-lucas6** [comment]
> In your guidelines, you recommend salted Blake2b as (Non-Password-Based) Key Derivation Function; however, there are the parameters salt, personalization, and you wrote that you can even feed more context information into the message parameter, but you haven't made any examples, on when you should put which sort of data into which parameter.

Yeah, the guidelines desperately need updating, but I'm working on some other projects at the moment and it's a big job. I should probably do it incrementally rather than trying to do entire sections at a time like I did before.

Unfortunately, there are no ideal KDFs. HKDF makes no sense outside the context of SHA-2 and suffers the limitations of HMAC as well as confusion about the salt. There's KMAC and KMACOXF for SHA-3, but they aren't as popular and I'm not sure why there's not just one function. BLAKE2X never took off. BLAKE3 has a `derive_key` mode, but there's no salt parameter and the context string has to be a constant. Salted BLAKE2b isn't really a KDF in that certain inputs and the output have fixed lengths, and not everybody implements it compared to regular BLAKE2b. There are NIST KDFs that have various optional parameters, and some of them are weird or should be avoided. Then you potentially have to be careful concatenating inputs with all of them, which ideally wouldn't be the case.

> Let's say, for example, that you have one key (from Argon2) and for whatever reason, you need to combine 4 ciphers, and therefore you need 4 x 256 bit of key material. Would it then be correct to use something like “cipher1”, “cipher2”, “cipher3” and “cipher4” as the personalization, the key from Argon2 as the message and just leave the salt blank (null)? Or what would be the correct usage here?

In that case, I would use the Argon2 output as the BLAKE2b key, "cipher1"... as the personalization, an all-zero salt, and no message if that's all the context you need. Alternatively, you could use the name of your application as the personalization and use a counter salt. Or you could use regular BLAKE2b without the personalization/salt parameters and feed that data into the message, but this requires using fixed-length inputs or [encoding the length](https://soatok.blog/2021/07/30/canonicalization-attacks-against-macs-and-signatures/) of each input.

If the input keying material isn't uniformly random (e.g., an ECDH shared secret), it should be hashed, and then the hash can be used as the BLAKE2b key to derive more keys (similar to HKDF-Extract then HKDF-Expand).

> And just out of curiosity, wouldn't it be possible too, to just use the key from Argon2 for ChaCha20 with a nonce of zero to generate 1024 bits of key stream, and then split the 1024-bit into 4 chunks with 256 bit each and just use them as keys for the 4 ciphers? Or would this lower the security compared to using Blake2b with the parameters?

Yes, with a uniformly random key (e.g., a randomly generated key or the output of a KDF), you can do that. I'm actually doing that in [Cahir](https://github.com/samuel-lucas6/Cahir?tab=readme-ov-file#specification).

However, it shouldn't be done with non-uniform keys (see above), and it's bad when you want domain separation or to include things like public keys in the key derivation. In general, you should use a collision-resistant hash function for key derivation. The main exception is when [deriving subkeys for nonce extension](https://datatracker.ietf.org/doc/draft-irtf-cfrg-xchacha/).

**Comment by BigPanda97** [comment]
> In that case, I would use the Argon2 output as the BLAKE2b key, "cipher1"... as the personalization, an all-zero salt, and no message if that's all the context you need. Alternatively, you could use the name of your application as the personalization and use a counter salt. Or you could use regular BLAKE2b without the personalization/salt parameters and feed that data into the message, but this requires using fixed-length inputs or [encoding the length](https://soatok.blog/2021/07/30/canonicalization-attacks-against-macs-and-signatures/) of each input.

Thanks, that's very useful. The only downside seems to be, that I couldn't find any test vectors for Blake2b with salt, personalization, and key parameters; only for the standard usage of hashing. So it appears to be difficult to test if the result is really correct.

> If the input keying material isn't uniformly random (e.g., an ECDH shared secret), it should be hashed, and then the hash can be used as the BLAKE2b key to derive more keys (similar to HKDF-Extract then HKDF-Expand).

Thanks, that's an important info.

> Yes, with a uniformly random key (e.g., a randomly generated key or the output of a KDF), you can do that. I'm actually doing that in [Cahir](https://github.com/samuel-lucas6/Cahir?tab=readme-ov-file#specification).

That's nice. So this could be an option too.

> I should probably do it incrementally rather than trying to do entire sections at a time like I did before.

This seems like a good idea. Your guidelines are really, really helpful.

**Comment by samuel-lucas6** [comment]
> Thanks, that's very useful. The only downside seems to be, that I couldn't find any test vectors for Blake2b with salt, personalization, and key parameters; only for the standard usage of hashing. So it appears to be difficult to test if the result is really correct.

[Here](https://github.com/samuel-lucas6/Geralt/blob/v3.1.0/src/Geralt.Tests/BLAKE2bTests.cs#L72) are some.

> That's nice. So this could be an option too.

I also forgot to say that you could just request a larger output with Argon2 and split it into separate keys.

**Comment by BigPanda97** [comment]
> [Here](https://github.com/samuel-lucas6/Geralt/blob/v3.1.0/src/Geralt.Tests/BLAKE2bTests.cs#L72) are some.

Ohh, thanks!

> I also forgot to say that you could just request a larger output with Argon2 and split it into separate keys.

But isn't Argon2 (Blake2b) limited to a maximum output size of 512 bits?

**Comment by samuel-lucas6** [comment]
> But isn't Argon2 (Blake2b) limited to a maximum output size of 512 bits?

One call to BLAKE2b is, but Argon2 creates a [variable-length hash function](https://en.wikipedia.org/wiki/Argon2#Variable-length_hash_function) by repeatedly calling BLAKE2b, albeit it does it in a weird way.

**Comment by BigPanda97** [comment]
> One call to BLAKE2b is, but Argon2 creates a [variable-length hash function](https://en.wikipedia.org/wiki/Argon2#Variable-length_hash_function) by repeatedly calling BLAKE2b, albeit it does it in a weird way.

Okay, that's interesting to know. But would you consider this "weird  way" to be 100% cryptographically secure?

**Comment by samuel-lucas6** [comment]
> Okay, that's interesting to know. But would you consider this "weird way" to be 100% cryptographically secure?

Well Argon2 is considered secure. It's just not the way I/most people would've done it. Instead of a typical KDF approach (like counter or feedback mode), for larger than 64-byte outputs, it hashes previous blocks and then truncates each hash for the output/derived key material. Without the truncation, you could compute subsequent blocks from previous blocks when each block is meant to be independent/shouldn't allow figuring out information about other keys.

**Comment by BigPanda97** [comment]
> Well Argon2 is considered secure. It's just not the way I/most people would've done it. Instead of a typical KDF approach (like counter or feedback mode), for larger than 64-byte outputs, it hashes previous blocks and then truncates each hash for the output/derived key material. Without the truncation, you could compute subsequent blocks from previous blocks when each block is meant to be independent/shouldn't allow figuring out information about other keys.

Thanks, that's nice to know. But I guess you would consider using Argon2 + Blake2b with key and personalization parameters as the KDF for the multiple keys to be a more conservative option, compared to the “weird way” of using Argon2 only, but with such a large output size, right?

**Comment by samuel-lucas6** [comment]
> Thanks, that's nice to know. But I guess you would consider using Argon2 + Blake2b with key and personalization parameters as the KDF for the multiple keys to be a more conservative option, compared to the “weird way” of using Argon2 only, but with such a large output size, right?

For Argon2, it shouldn't really matter. With something like PBKDF2, it does matter, and you should use a short output and then expand it using a regular KDF due to its bad design.

**Comment by BigPanda97** [comment]
> For Argon2, it shouldn't really matter. With something like PBKDF2, it does matter, and you should use a short output and then expand it using a regular KDF due to its bad design.

Thanks, that's nice to know!
I'll close this now because all my questions are solved now. Thanks!
